config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  
  
  
  get '/calendar/events', to: "events#index" , as: :events
  post '/calendar/events', to: "events#create", as: :event_path
  get '/calendar/events/new', to: "events#new", as: :new_event
  get '/calendar/events/:id', to: "events#show", as: :event
  patch '/calendar/events/:id', to: "events#update"
  delete '/calendar/events/:id', to: "events#destroy", as: :delete_event
  get '/calendar/events/:id/edit', to: 'events#edit', as: :edit_event
  
  
  
  
  get '/calendar/groups', to: "groups#index" , as: :groups
  post '/calendar/groups', to: "groups#create", as: :group_path
  get '/calendar/groups/new', to: "groups#new", as: :new_group
  get '/calendar/groups/:id', to: "groups#show", as: :group
  patch '/calendar/groups/:id', to: "groups#update"
  delete '/calendar/groups/:id', to: "groups#destroy", as: :delete_group
  get '/calendar/groups/:id/edit', to: 'groups#edit', as: :edit_group
  
  
  
  get '/calendar', to: "posts#index"
  get '/calendar/day/:id', to: "posts#show"
  get '/calendar/:id', to: "posts#index" , as: :calendar_roll





  # Defines the root path route ("/")
  root "posts#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dayer.rb
class Dayer # name Calendar for some reason doesn't work 
  

  def self.calendar(id_param)
    if id_param == nil
      month = Date.today.all_month.to_a
    elsif id_param > 0
      month = Date.today.months_since(id_param).all_month.to_a
    else
      month = Date.today.months_ago(id_param.abs).all_month.to_a
    end
    this_months_events = data_getter(month[0])
    cal_hsh= setter(month, this_months_events)
    return cal_hsh#, this_months_events
  end 
  

  private
  def self.setter(month, this_months_events)
    cal_hsh = {}
    for key in month
      cal_hsh[key] = []
    end
    for day in month
      for event in this_months_events
        if event.date_to == nil
          to = event.date_from
        else
          to = event.date_to
        end
        for days_of_event in (event.date_from..to).to_a
          if day == days_of_event
            cal_hsh[day] << event
          end
        end
      end

    end
    return cal_hsh
  end

  def self.data_getter(date)
    start = date.beginning_of_month
    end_of_m =  date.end_of_month
    starts_within_month = Event.where("date_from BETWEEN ? AND ?", start, end_of_m)
    ends_within_month = Event.where("date_to BETWEEN ? AND ?", start, end_of_m)
      

      
  
    starts_within_month = starts_within_month.to_a
    ends_within_month = ends_within_month.to_a
    joint = starts_within_month | ends_within_month
    return joint
  
  end



end

app/models/event.rb
class Event < ApplicationRecord
    validates :time_from, :time_to, :date_from, :name, :group, presence: :true

    def starts_today?
        if self.date_from == Date.today 
            return true

        else
            return false
        end

    end
    def ends_today?
        if self.date_to == Date.today 
            return true

        elsif self.date_to.nil? || self.date_to == self.date_from
            self.starts_today?

        else
            return false
        end

    end







end

app/models/group.rb
class Group < ApplicationRecord
    validates :group, :color, presence: :true

    def is_used?
        events = Event.all
        a = events.map do |event|
            event.group
        end
        if a.include? self.group
            return true
        else
            false
        end
    end


end

app/models/weather_api.rb
require "httparty"

class WeatherApi
  include HTTParty

  base_uri  'http://api.weatherapi.com/v1'

  def initialize()
    @api_key = 'a51d407ac2184a4385a193241240405'
  end

  def weather_by_city(city)
    self.class.get("/current.json?key=#{@api_key}&q=#{city}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :set_event, only: [:show, :edit, :update, :destroy]
    before_action :load_groups, only: [:index,:new,:create, :edit, :update]

    def index
        @events = Event.all

        
    end


    def show

    end

    def new
        @event = Event.new
    end

    def create
        
        @event = Event.new(event_params)
        
        p '_____________________________'
        p '_____________________________'
        puts event_params[:date_from].class
        if @event.save
            event_start_date = Date.strptime(event_params[:date_from])
            redirect_to calendar_roll_path((12 * (event_start_date.year - Date.today.year) + event_start_date.month - Date.today.month))
        else
            render 'new', status: :unprocessable_entity
        end
    end
    
    def edit
    end
    
    def update
        
        if @event.update(event_params)
            event_start_date = Date.strptime(event_params[:date_from])
            redirect_to calendar_roll_path((12 * (event_start_date.year - Date.today.year) + event_start_date.month - Date.today.month))
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        @event.delete
        redirect_to calendar_url
    end


    private
    def event_params
        params.require(:event).permit(:name, :time_from, :time_to, :date_from,:date_to, :body, :group)
    end

    def set_event
        @event = Event.find(params[:id])

    end
    def load_groups
        @groups = Group.all

    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    before_action :set_group, only: [:edit, :update, :destroy]


    def index
        @groups = Group.all

        
    end



    def new
        @group = Group.new
    end

    def create
        @group = Group.new(group_params)

        if @group.save
            redirect_to groups_url
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @group.update(group_params)
            redirect_to groups_url
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        @group.delete
        redirect_to groups_url
    end


    private
    def group_params
        params.require(:group).permit(:group, :color)
    end

    def set_group
        @group = Group.find(params[:id])

    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def home
        
        api = WeatherApi.new()
        @weather = api.weather_by_city('zilina')
        @month_view= Dayer.calendar(0)
        


    end
    
    def index
        @id = params[:id].to_i
        @month_view= Dayer.calendar(params[:id].to_i)
    end
    
    def show

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event, class:'grid grid-cols-1 gap-y-6' do |f|%>
    <% if @event.errors.any? %>
        <ul>
        <%@event.errors.each do |error| %>
            <li class='text-sm text-fuchsia-700'><%=error.full_message %></li>
        <% end %>
        </ul>
    <% end %>
    <div>
        <%= f.label :time_from, class:"font-semibold text-blue-600"%>
        <%= f.time_field  :time_from, class: 'mt-1 w-full border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md' %>
    </div>
    <div>
        <%= f.label :date_from, class:"font-semibold text-blue-600"%>
        <%= f.date_field   :date_from, class: 'mt-1 w-full border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md' %>
    </div>
    <div>
        <%= f.label :time_to, class:"font-semibold text-blue-600"%>
        <%= f.time_field  :time_to, class: 'mt-1 w-full border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md'%>
    </div>
    <div>
        <%= f.label :date_to, class:"font-semibold text-blue-600"%>
        <%= f.date_field   :date_to, class: 'mt-1 w-full border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md'%>
    </div>
    <div>
        <%= f.label :name, class:"font-semibold text-blue-600"%>
        <%= f.text_field :name, class: 'mt-1 w-full border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md' %>
    </div>
    <div>
        <%= f.label :body, class:"font-semibold text-blue-600"%>
        <%= f.text_area :body, class: 'mt-1 w-full border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md'%>
    </div>

    <div class='flex'>

     <%@groups.each do |group|%>
             <%= f.label  group.group.to_s, class:"font-semibold mx-4"%>
             <%= f.radio_button :group, group.group.to_s,  class: 'mt-1 border border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md'%>
     <%end%>
    </div>


    <div class=' flex justify-end'>
      <%= f.submit  class:'bg-indigo-600 hover:bg-indigo-800 text-white rounded-lg px-4 py-2'%>
    <div>
<%end%>

app/views/events/edit.html.erb
<div class='flex justify-between'>
  <h1 class="text-2xl font-semibold">Edit Event</h1>
  <%=link_to '< back to events', events_path, class: 'px-3 py-1.5 hover:drop-shadow-lg text-gray-500 drop-shadow' %>
</div>

<div class='mt-2'>
  <%=render 'form' %>
</div>

app/views/events/index.html.erb
<div class='flex-col '>
  <div>
   <%=link_to '< back to Calendar', calendar_path, class: 'px-3 py-1.5 hover:drop-shadow-lg text-gray-500 drop-shadow' %>
    <div class='flex justify-end'>
     <%=link_to 'New Event', new_event_path, class: 'px-3 py-1.5 border hover:bg-indigo-400 text-indigo-500 border-indigo-500 rounded-lg shadow-lg '%>
     <%=link_to 'Edit Groups', groups_path, class: 'px-3 py-1.5 border hover:bg-amber-400 text-orange-500 border-amber-500 rounded-lg shadow-lg ml-2'%>
    </div>
  </div>
  <section class='mt-6 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4  gap-x-6 gap-y-6'>
      <% @events.each do |event| %>
        <% a = Group.where(group: "#{event.group}")%>
        <% a = a[0]%>
        <div style="background-color: <%= a.color %>" class='flex-col justify-between shadow-md p-4 border border-indigo-400 transition duration-300 hover:shadow-lg rounded-2xl'>
          <div class='flex justify-center'>
          <h2 class='text-lg font-medium'><%=link_to event.name, event%></h2>
          </div>
          <div class='p-4 flex-col'>
          <h1><%= event.time_from.to_s[11..15]%>, <%= event.date_from%></h1>
          <h1><%= event.time_to.to_s[11..15]%>, <%= event.date_to%></h1>
          <h1><%= event.body%></h1>
          </div>
          <div class='flex justify-center items-center'>
              <%=link_to 'Edit', edit_event_path(event.id), class: 'px-3 py-1.5 border hover:bg-yellow-400 text-amber-500 border-yellow-500 rounded-lg shadow-lg '%>
              <%=button_to 'Delete', event, method: :delete, class: 'ml-1 px-3 py-1.5 bg-pink-100 hover:bg-pink-300 opacity-60  hover:shadow-xl text-rose-600 rounded-lg shadow-lg'%>
          </div>
        </div>
      <% end %>
  </section> 
</div>



<footer class="w-full h-10 relative bottom-0 flex justify-center mt-2">
</footer> 

app/views/events/new.html.erb
 <div class='flex justify-between'>
  <h1 class="text-2xl font-semibold">New Event</h1>
  <%=link_to '< back to events', events_path, class: 'px-3 py-1.5 hover:drop-shadow-lg text-gray-500 drop-shadow' %>
</div>

<div class='mt-2'>
  <%=render 'form' %>

</div>

app/views/events/show.html.erb
<% a = Group.where(group: "#{@event.group}")%>
<% a = a[0]%>
<%=link_to 'back to Calendar', calendar_path, class: 'px-3 py-1.5 border hover:bg-indigo-400 text-indigo-500 border-indigo-500 rounded-lg shadow-lg '%>
<div class='flex justify-center'>
    <section style="background-color: <%= a.color%>" class='flex-col p-4 my-6 rounded-xl border border-sky-400 shadow'>
            <h1><%= @event.name%></h1>
            <h1><%= @event.time_from.to_s[11..15]%> <%= @event.date_from.strftime('%m/%d/%Y')%></h1>
            <h1><%= @event.time_to.to_s[11..15]%> <%= @event.date_to.strftime('%m/%d/%Y') unless @event.date_to == nil %></h1>
            <h1><%= @event.group%></h1>
            <h1><%= @event.body%></h1>
            <div class='flex mt-2 justify-center'>
                <%=link_to 'Edit', edit_event_path(@event.id), class: 'px-3 py-1.5 border hover:bg-indigo-400 text-indigo-500 border-indigo-500 rounded-lg shadow-lg '%>
                <%=button_to 'Delete', @event, method: :delete, class: 'ml-1 px-3 py-1.5 bg-pink-100 hover:bg-pink-300 opacity-60  hover:shadow-xl text-rose-600 rounded-lg shadow-lg'%>
    </section>
</div>

app/views/groups/_form.html.erb
<%= form_with model: @group, class:'grid grid-col-1 gap-y-6' do |f|%>
    <% if @group.errors.any? %>
        <ul>
        <%@group.errors.each do |error| %>
            <li class='text-sm text-fuchsia-700'><%=error.full_message%></li>
        <% end %>
        </ul>
    <% end %>
    <div>
        <%= f.label :group, class:"font-semibold text-blue-600"%>
        <%= f.text_field :group, class:'mt-1 w-full border-0 ring-2 px-3 py-1.5 ring-indigo-600 rounded-md'%>
    </div>
    <div>
        <%= f.label :color, class:"font-semibold text-blue-600"%>
        <%= f.color_field  :color%>
    </div>

    <div class='flex justify-end'>
     <%= f.submit class:'bg-indigo-600 hover:bg-indigo-800 text-white rounded-lg px-4 py-2 '%>
    </div>
<%end%>

app/views/groups/edit.html.erb
<div class='flex justify-between'>
 <h1 class="text-2xl font-semibold">Edit Group</h1>
 <%=link_to '< back to groups', groups_path, class: 'px-3 py-1.5 hover:drop-shadow-lg text-gray-500 drop-shadow' %>
</div>

<div class='mt-2'>
 <%=render 'form' %>
</div>

app/views/groups/index.html.erb
<div class='flex-col '>
  <div class='flex justify-between'>
    <%=link_to '<- back', events_path, class: 'px-3 py-1.5 hover:drop-shadow-lg text-gray-500 drop-shadow' %>
   <%=link_to 'New Group', new_group_path, class: 'px-3 py-1.5 border hover:bg-amber-400 text-orange-400 border-amber-500 rounded-lg shadow-lg ml-2'%>
  </div>
  <section class='mt-6 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5  gap-x-6 gap-y-6'>
      <% @groups.each do |group| %>
        <div class='event flex-col justify-between shadow-md p-4 border border-indigo-400 transition duration-300 hover:shadow-lg rounded-2xl' style="background-color: <%= group.color %>">
          <div class='flex justify-center'>
          <h2 class='text-lg font-medium'><%=link_to group.group, edit_group_path(group)%></h2>
          </div>
          <div class='p-4 flex-col'>
          <h1><%= group.color%></h1>
          </div>
          <div class='flex justify-center items-center'>
              <%=link_to 'Edit', edit_group_path(group), class: 'px-3 py-1.5 border hover:bg-yellow-400 text-amber-500 border-yellow-500 rounded-lg shadow-lg '%>
                <%unless group.is_used?%>
                    <%=button_to 'Delete', group, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'ml-1 px-3 py-1.5 bg-pink-100 hover:bg-pink-300 opacity-60  hover:shadow-xl text-rose-600 rounded-lg shadow-lg'%>
                <%end%>
          </div>
        </div>
      <% end %>
  </section> 
</div>

<footer class="w-full h-10 relative bottom-0 flex justify-center mt-6">
  <p class='text-gray-400'>You can delete only unused groups</p>
  
</footer> 

app/views/groups/new.html.erb
<div class='flex justify-between'>
 <h1 class="text-2xl font-semibold">New Group</h1>
 <%=link_to '< back to groups', groups_path, class: 'px-3 py-1.5 hover:drop-shadow-lg text-gray-500 drop-shadow' %>
</div>

<div class='mt-2'>
 <%=render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-orange-100">
  <head>
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-4 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/home.html.erb
<div class='flex justify-end'>
  <%= link_to 'Calendar', calendar_path, class: 'px-3 py-1.5 border hover:bg-green-300 text-xl text-green-400 rounded-lg shadow-sm mr-4' %>
  <%= link_to 'New Event', new_event_path, class: 'px-3 py-1.5 border hover:bg-indigo-400 text-indigo-500 rounded-lg shadow-sm' %>
</div>

<div class='w-full flex-col mt-4'>
  <div class='flex justify-center'>
    <h1 class='text-xl'><%= Date.today.strftime('%m/%d/%Y') %></h1>
  </div>

  <div class='flex justify-between mt-6'>
    <div class='w-1/3'>
      <div class='flex border justify-between border-cyan-400 bg-cyan-300 rounded-lg items-center p-4 mr-6'>
        <div class='flex-col mr-2'>
          <h1 class='text-xl'><%= @weather['location']['name'] %></h1>
          <h1><%= @weather['location']['country'] %></h1>
          <h1><%= @weather['location']['lat'] %>, <%= @weather['location']['lon'] %></h1>
        </div>
        <div>
          <img src="<%= @weather['current']['condition']['icon'] %>" alt="icon of current weather">
          <h1><%= @weather['current']['temp_c'] %>°C</h1>
        </div>
      </div>
    </div>

    <div class='w-2/3 h-[680px] border rounded-lg p-4 bg-gradient-to-r from-green-300 via-emerald-300 to-teal-300 overflow-hidden'>
      <h1 class='text-3xl'>Today's events:</h1>
      <% if @month_view[Date.today].empty? %>
        <div class='flex justify-center mt-4'>
          <h1 class='text-gray-400'>No events for today</h1>
        </div>
      <% end %>
        <hr>
      <div class="relative h-[600px] mt-2 overflow-hidden">
        <% 24.times do |hour| %>
          <div class="absolute w-full border-b border-gray-100 text-left  pr-2 text-xs" style="top: <%= hour * 25 %>px;">
            <%= "#{hour}:00" %>
          </div>
        <% end %>
        


        <% columns = [] %>
        
        <% @month_view[Date.today].each do |event| %>
          <% a = Group.find_by(group: event.group) %>
          <% col = @month_view[Date.today].find_index(event)%>
          <% thickness = 96/@month_view[Date.today].count()%>
          <% start_time = (event.time_from.hour*60 + event.time_from.min)/60.0%>
          <% end_time = (event.time_to.hour*60 + event.time_to.min)/60.0%>
          <% if event.starts_today? && event.ends_today?%>
            <a href="/calendar/events/<%= event.id %>" style="background-color: <%= a.color %>; top: <%= start_time * 25 -8%>px; left: <%= 4 + (col) * thickness %>%; width: <%=thickness%>%; height: <%= (end_time - start_time)*25%>px;" class="absolute p-2 rounded-lg text-white text-sm overflow-hidden">
               <h1 class='flex justify-center text-black'><%=event.name%></h1>
            </a>

          <% elsif event.starts_today? && !event.ends_today?%>
            <a href="/calendar/events/<%= event.id %>" style="background-color: <%= a.color %>; top: <%= start_time * 25 -8%>px; left: <%=4 + (col) * thickness %>%; width: <%=thickness%>%; height: <%= (24 - start_time)*25%>px;" class="absolute p-2 rounded-lg text-white text-sm overflow-hidden">
               <h1 class='flex justify-center text-black'><%=event.name%></h1>
            </a>
          <% elsif !event.starts_today? && event.ends_today?%>
            <a href="/calendar/events/<%= event.id %>" style="background-color: <%= a.color %>; top: -8px; left: <%=4 + (col) * thickness %>%; width: <%=thickness%>%; height: <%= (end_time)*25%>px;" class="absolute p-2 rounded-lg text-white text-sm overflow-hidden">
               <h1 class='flex justify-center text-black'><%=event.name%></h1>
            </a>
          <% elsif !event.starts_today? && !event.ends_today?%>
            <a href="/calendar/events/<%= event.id %>" style="background-color: <%= a.color %>; top: -8px; left: <%=4 + (col) * 25 %>%; width: <%=thickness%>%; height: <%= (24)*25%>px;" class="absolute p-2 rounded-lg text-white text-sm overflow-hidden">
               <h1 class='flex justify-center text-black'><%=event.name%></h1>
            </a>
          <% end %>
        <% end %>


        
      </div>
    </div>
  </div>
</div>


<footer class="w-full h-10 relative bottom-0 flex justify-center mt-2">
</footer> 

app/views/posts/index.html.erb
<%= link_to '< Home', root_path, class: 'px-3 py-1.5 hover:drop-shadow-lg text-gray-500 drop-shadow' %>
<div class='flex justify-end m-1'>
  <%= link_to 'Events', events_path, class: 'px-3 py-1.5 border hover:bg-indigo-400 text-indigo-500 border-indigo-500 rounded-lg shadow-lg mr-2' %>
  <%= link_to 'New Event', new_event_path, class: 'px-3 py-1.5 border hover:bg-indigo-400 text-indigo-500 border-indigo-500 rounded-lg shadow-lg' %>
</div>
<hr class='bg-gray-400 h-0.5'>
<div class='flex items-center justify-between m-2'>
  <%= link_to '<<', calendar_roll_path(@id - 1), class: 'px-3 py-1.5 border hover:bg-green-300 text-3xl text-green-400 border-green-400 rounded-lg shadow-lg' %>
  <div class='flex flex-col justify-center items-center'>
    <h1 class='text-4xl'><%= @month_view.keys[0].strftime('%B') %></h1>
    <h5 class='text-xl'><%= @month_view.keys[0].year %></h5>
  </div>
  <%= link_to '>>', calendar_roll_path(@id + 1), class: 'px-3 py-1.5 border hover:bg-green-300 text-3xl text-green-400 border-green-400 rounded-lg shadow-lg' %>
</div>

<div class='flex-col justify-between shadow-md p-4 border border-green-400 bg-green-200 rounded-xl'>
  <section class='mt-6 grid grid-cols-7 gap-x-6 gap-y-6'>
    <h1 class='text-xs sm:text-sm md:text-lg lg:text-xl'>Monday</h1>
    <h1 class='text-xs sm:text-sm md:text-lg lg:text-xl'>Tuesday</h1>
    <h1 class='text-xs sm:text-sm md:text-lg lg:text-xl'>Wednesday</h1>
    <h1 class='text-xs sm:text-sm md:text-lg lg:text-xl'>Thursday</h1>
    <h1 class='text-xs sm:text-sm md:text-lg lg:text-xl'>Friday</h1>
    <h1 class='text-xs sm:text-sm md:text-lg lg:text-xl'>Saturday</h1>
    <h1 class='text-xs sm:text-sm md:text-lg lg:text-xl'>Sunday</h1>
  </section>
    <hr class='bg-emerald-400 h-1 mt-4'>
  <section class='mt-6 grid grid-cols-7 gap-x-6 gap-y-6'>
    <% first_day_of_month = @month_view.keys[0].beginning_of_month %>
    <% last_day_of_month = @month_view.keys[0].end_of_month %>
    <% first_calendar_day = first_day_of_month.beginning_of_week(:monday) %>
    <% last_calendar_day = last_day_of_month.end_of_week(:monday) %>

    <% (first_calendar_day..last_calendar_day).each do |date| %>
      <div class='flex-col p-1 border border-green-400 rounded-lg hover:border-green-500 transition duration-100 hover:shadow <%= "text-gray-400" if date.month != first_day_of_month.month %> <%= "bg-gradient-to-r from-green-300 via-emerald-300 to-teal-300" if date == Date.today %>'>
        <%= date.day %>
        <% if @month_view[date] %>
          <% @month_view[date].each do |event| %>
            <% a = Group.find_by(group: event.group) %>
          
              <a href="/calendar/events/<%=event.id%>" style="background-color: <%= a.color %>" class="block p-2 rounded-lg shadow-md">
                <% if event.date_to.nil? || event.date_to == event.date_from %>
                  <h1 class='text-sm'><%= event.time_from.to_s[10..15] %> - <%= event.time_to.to_s[10..15] %></h1>
                <% elsif date == event.date_from %>
                  <h1 class='text-sm'><%= event.time_from.to_s[10..15] %></h1>
                <% elsif date == event.date_to %>
                  <h1 class='text-sm'><%= event.time_to.to_s[10..15] %></h1>
                <% end %>
                <h1 class='text-sm'><%=event.name %></h1>
              </a>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </section>
</div>


<footer class="w-full h-10 relative bottom-0 flex justify-center mt-2">
</footer> 